name: Build and Release Electron App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual triggering

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM, and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install snapcraft (Ubuntu only)
        if: runner.os == 'Linux'
        run: sudo snap install snapcraft --classic

      - name: Install dependencies (Ubuntu only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libarchive-tools

      - name: Build and Release Electron App
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.RELEASE_PAT }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          package_root: frontend
